# Generated by Django 6.0.2 on 2026-02-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='services/')),
                ('orden', models.IntegerField(default=0, help_text='Para decidir cuál va primero')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden'],
            },
        ),
    ]
