# Generated by Django 6.0.2 on 2026-02-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icono',
            field=models.CharField(default='fa-gear', help_text='Clase de FontAwesome (ej: fa-code)', max_length=50),
        ),
    ]
