# Generated by Django 6.0.2 on 2026-02-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
