# Generated by Django 6.0.2 on 2026-02-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='mapa_embed',
            field=models.TextField(blank=True, help_text='Pega aca el código embed de Google Maps', verbose_name='Código del Mapa (Google Maps)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ubicacion_texto',
            field=models.TextField(blank=True, help_text="Instrucciones escritas (Ej: 'Frente a la plaza...')"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='ubicacion_titulo',
            field=models.CharField(default='Nuestra Ubicación', help_text='Ej: Cómo llegar, Dónde estamos', max_length=100),
        ),
    ]
